INSERT INTO developers VALUE (1,'Pavlo', 30,'male');
INSERT INTO developers VALUE (2,'Max', 31,'male');
INSERT INTO developers VALUE (3,'Julia', 31,'female');
INSERT INTO developers VALUE (4,'Natalia', 28,'female');
INSERT INTO developers VALUE (5,'Svitlana', 27,'female');
INSERT INTO developers VALUE (6,'Andriy', 33,'male');
INSERT INTO developers VALUE (7,'Oleksiy', 36,'male');

INSERT INTO skills VALUE (1,'Java','Junior');
INSERT INTO skills VALUE (2,'Java','Middle');
INSERT INTO skills VALUE (3,'Java','Senior');
INSERT INTO skills VALUE (4,'C++','Junior');
INSERT INTO skills VALUE (5,'C++','Middle');
INSERT INTO skills VALUE (6,'C++','Senior');
INSERT INTO skills VALUE (7,'C#','Junior');
INSERT INTO skills VALUE (8,'C#','Middle');
INSERT INTO skills VALUE (9,'C#','Senior');
INSERT INTO skills VALUE (10,'JS','Junior');
INSERT INTO skills VALUE (11,'JS','Middle');
INSERT INTO skills VALUE (12,'JS','Senior');
INSERT INTO skills VALUE (13,'Python','Junior');
INSERT INTO skills VALUE (14,'Python','Middle');
INSERT INTO skills VALUE (15,'Python','Senior');

INSERT INTO companies VALUE (1,'ELITEX',1992);
INSERT INTO companies VALUE (2,'SoftServe',1997);
INSERT INTO companies VALUE (3,'EPAM',2005);
INSERT INTO companies VALUE (4,'GlobalLogic',2000);
INSERT INTO companies VALUE (5,'Luxoft',2002);
INSERT INTO companies VALUE (6,'Ciklum',2002);

INSERT INTO customers VALUE (1,'Rozetka','https://rozetka.com.ua/');
INSERT INTO customers VALUE (2,'Foxtrot','https://www.foxtrot.com.ua/');
INSERT INTO customers VALUE (3,'Comfy','https://comfy.ua');
INSERT INTO customers VALUE (4,'Allo','https://allo.ua/');
INSERT INTO customers VALUE (5,'Moyo','https://www.moyo.ua/');

INSERT INTO projects VALUE (1,'Website','create new website for customer',1,1);
INSERT INTO projects VALUE (2,'MobileApp','create mobile application',3,1);
INSERT INTO projects VALUE (3,'Game','create mobile game for customer',3,2);
INSERT INTO projects VALUE (4,'Database','create database for customer buisness logic',2,2);
INSERT INTO projects VALUE (5,'Software platform','Building a new software platform or program',2,3);
INSERT INTO projects VALUE (6,'Security ','developing a security patch for existing software',4,3);
INSERT INTO projects VALUE (7,'Data Management','Developing a backup and restoration strategy',5,3);
INSERT INTO projects VALUE (8,'Network System Upgrades','Expanding the network INTO a new area in an office building',4,4);
INSERT INTO projects VALUE (9,'Website Upgrades','Upgrades  website',6,5);
INSERT INTO projects VALUE (10,'MobileApp Upgrades','Upgrades mobile application',6,5);
INSERT INTO projects VALUE (11,'Game Upgrades','Upgrades mobile game for customer',2,5);
INSERT INTO projects VALUE (12,'Database Security','security patch for database for customer buisness logic',1,5);

INSERT INTO developers_skills VALUE (1,2);
INSERT INTO developers_skills VALUE (1,10);
INSERT INTO developers_skills VALUE (2,1);
INSERT INTO developers_skills VALUE (3,1);
INSERT INTO developers_skills VALUE (3,7);
INSERT INTO developers_skills VALUE (4,10);
INSERT INTO developers_skills VALUE (5,1);
INSERT INTO developers_skills VALUE (6,13);
INSERT INTO developers_skills VALUE (7,4);

INSERT INTO developers_projects VALUE (1,2);
INSERT INTO developers_projects VALUE (1,3);
INSERT INTO developers_projects VALUE (1,4);
INSERT INTO developers_projects VALUE (1,6);
INSERT INTO developers_projects VALUE (1,8);
INSERT INTO developers_projects VALUE (1,10);
INSERT INTO developers_projects VALUE (2,1);
INSERT INTO developers_projects VALUE (2,5);
INSERT INTO developers_projects VALUE (2,7);
INSERT INTO developers_projects VALUE (2,9);
INSERT INTO developers_projects VALUE (2,11);
INSERT INTO developers_projects VALUE (3,12);
INSERT INTO developers_projects VALUE (3,1);
INSERT INTO developers_projects VALUE (4,2);
INSERT INTO developers_projects VALUE (4,3);
INSERT INTO developers_projects VALUE (5,2);
INSERT INTO developers_projects VALUE (5,11);
INSERT INTO developers_projects VALUE (6,1);
INSERT INTO developers_projects VALUE (6,2);
INSERT INTO developers_projects VALUE (6,3);
INSERT INTO developers_projects VALUE (6,7);
INSERT INTO developers_projects VALUE (7,4);
INSERT INTO developers_projects VALUE (7,5);
INSERT INTO developers_projects VALUE (7,6);
INSERT INTO developers_projects VALUE (7,7);
INSERT INTO developers_projects VALUE (7,8);
INSERT INTO developers_projects VALUE (1,12);
INSERT INTO developers_projects VALUE (6,10);
INSERT INTO developers_projects VALUE (5,9);
