insert into developers value (1,'Pavlo', 30,'male');
insert into developers value (2,'Max', 31,'male');
insert into developers value (3,'Julia', 31,'female');
insert into developers value (4,'Natalia', 28,'female');
insert into developers value (5,'Svitlana', 27,'female');
insert into developers value (6,'Andriy', 33,'male');
insert into developers value (7,'Oleksiy', 36,'male');

insert into skills value (1,'Java','Junior');
insert into skills value (2,'Java','Middle');
insert into skills value (3,'Java','Senior');
insert into skills value (4,'C++','Junior');
insert into skills value (5,'C++','Middle');
insert into skills value (6,'C++','Senior');
insert into skills value (7,'C#','Junior');
insert into skills value (8,'C#','Middle');
insert into skills value (9,'C#','Senior');
insert into skills value (10,'JS','Junior');
insert into skills value (11,'JS','Middle');
insert into skills value (12,'JS','Senior');
insert into skills value (13,'Python','Junior');
insert into skills value (14,'Python','Middle');
insert into skills value (15,'Python','Senior');

insert into companies value (1,'ELITEX',1992);
insert into companies value (2,'SoftServe',1997);
insert into companies value (3,'EPAM',2005);
insert into companies value (4,'GlobalLogic',2000);
insert into companies value (5,'Luxoft',2002);
insert into companies value (6,'Ciklum',2002);

insert into customers value (1,'Rozetka','https://rozetka.com.ua/');
insert into customers value (2,'Foxtrot','https://www.foxtrot.com.ua/');
insert into customers value (3,'Comfy','https://comfy.ua');
insert into customers value (4,'Allo','https://allo.ua/');
insert into customers value (5,'Moyo','https://www.moyo.ua/');

insert into projects value (1,'Website','create new website for customer',1,1);
insert into projects value (2,'MobileApp','create mobile application',3,1);
insert into projects value (3,'Game','create mobile game for customer',3,2);
insert into projects value (4,'Database','create database for customer buisness logic',2,2);
insert into projects value (5,'Software platform','Building a new software platform or program',2,3);
insert into projects value (6,'Security ','developing a security patch for existing software',4,3);
insert into projects value (7,'Data Management','Developing a backup and restoration strategy',5,3);
insert into projects value (8,'Network System Upgrades','Expanding the network into a new area in an office building',4,4);
insert into projects value (9,'Website Upgrades','Upgrades  website',6,5);
insert into projects value (10,'MobileApp Upgrades','Upgrades mobile application',6,5);
insert into projects value (11,'Game Upgrades','Upgrades mobile game for customer',2,5);
insert into projects value (12,'Database Security','security patch for database for customer buisness logic',1,5);

insert into developer_skills value (1,1,2);
insert into developer_skills value (2,1,10);
insert into developer_skills value (3,2,1);
insert into developer_skills value (4,3,1);
insert into developer_skills value (5,3,7);
insert into developer_skills value (6,4,10);
insert into developer_skills value (7,5,1);
insert into developer_skills value (8,6,13);
insert into developer_skills value (9,7,4);

insert into developer_project value (1,1,2);
insert into developer_project value (2,1,3);
insert into developer_project value (3,1,4);
insert into developer_project value (4,1,6);
insert into developer_project value (5,1,8);
insert into developer_project value (6,1,10);
insert into developer_project value (7,2,1);
insert into developer_project value (8,2,5);
insert into developer_project value (9,2,7);
insert into developer_project value (10,2,9);
insert into developer_project value (11,2,11);
insert into developer_project value (12,3,12);
insert into developer_project value (13,3,1);
insert into developer_project value (14,4,2);
insert into developer_project value (15,4,3);
insert into developer_project value (16,5,2);
insert into developer_project value (17,5,11);
insert into developer_project value (18,6,1);
insert into developer_project value (19,6,2);
insert into developer_project value (20,6,3);
insert into developer_project value (21,6,7);
insert into developer_project value (22,7,4);
insert into developer_project value (23,7,5);
insert into developer_project value (24,7,6);
insert into developer_project value (25,7,7);
insert into developer_project value (26,7,8);
